# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 02:47
from __future__ import unicode_literals

import articleware.utils.images
from django.db import migrations, models
import siteware.backends.storages.default


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, null=True, storage=siteware.backends.storages.default.MediaFilesStorage(), upload_to=articleware.utils.images.uploadto_image_to_year_month_uuid_lg),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_md',
            field=models.ImageField(max_length=255, null=True, storage=siteware.backends.storages.default.MediaFilesStorage(), upload_to=articleware.utils.images.uploadto_image_to_year_month_uuid_md),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_sm',
            field=models.ImageField(max_length=255, null=True, storage=siteware.backends.storages.default.MediaFilesStorage(), upload_to=articleware.utils.images.uploadto_image_to_year_month_uuid_sm),
        ),
    ]
