# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0004_auto_20160124_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.BooleanField(default=False, help_text='If this is an internal blog article.', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, help_text='If this is a featured article', verbose_name='Featured'),
        ),
    ]
