# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:39
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0005_auto_20160127_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='targets',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated regions. Ex: Canada, Mexico, United States. Blank for Worldwide', through='articleware.TargetingTaggedItem', to='articleware.TargetingTag', verbose_name='Targeting Tags'),
        ),
    ]
