# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0006_auto_20160202_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=taggit.managers.TaggableManager(help_text='Comma-separated article categories. Ex: Technology, Finance etc.', through='articleware.CategoryTaggedItem', to='articleware.CategoryTag', verbose_name='Category Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private'), ('Archived', 'Archived')], default='Private', help_text='Visibility. Public=ByAll, Unlisted=ByLink, Private=ByNobody, Archived=Private+Historical.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Comma-separated article content tags. Ex: Android, iPhone, iPad Pro, Life, Happiness etc.', through='articleware.ContentTaggedItem', to='articleware.ContentTag', verbose_name='Content Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='targets',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated article regions. Ex: Canada, Mexico, United States. (blank = not region specific)', through='articleware.TargetingTaggedItem', to='articleware.TargetingTag', verbose_name='Region Tags'),
        ),
    ]
