# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0007_auto_20160203_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin',
            field=models.BooleanField(default=False, help_text='If this is an internal admin article. Ex: privacy policy or terms & conditions', verbose_name='Admin'),
        ),
    ]
