# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:23
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0011_auto_20160208_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=taggit.managers.TaggableManager(help_text='Comma-separated article categories. Ex: Technology, Finance etc.', through='articleware.CategoryTaggedItem', to='articleware.CategoryTag', verbose_name='Category Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Comma-separated article content tags. Ex: Android, iPhone, iPad Pro, Life, Happiness etc.', through='articleware.ContentTaggedItem', to='articleware.ContentTag', verbose_name='Content Tags'),
        ),
    ]
