# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0013_auto_20160216_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for this post', null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(255)], verbose_name='Description'),
        ),
    ]
