# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0014_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('MAP', 'MAP')], default='IMAGE', max_length=10),
        ),
    ]
