# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0015_auto_20160409_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='admin',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.BooleanField(default=False, help_text='If this is a site page article. Ex: privacy policy or terms & conditions', verbose_name='Page'),
        ),
    ]
