# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:33
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0016_auto_20160414_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='targets',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated categories. (Ex: Technology, Finance etc.)', through='articleware.CategoryTaggedItem', to='articleware.CategoryTag', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Comma-separated tags. (Ex: Android, iPhone, Life, Travel etc.)', through='articleware.ContentTaggedItem', to='articleware.ContentTag', verbose_name='Tags'),
        ),
    ]
