# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0017_auto_20160417_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='flavor',
            field=models.CharField(choices=[('Article', 'Article'), ('Blog', 'Blog'), ('Page', 'Page')], default='Article', help_text='Article type. (Ex: Article, Blog, Page).', max_length=20, verbose_name='Flavor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Author of this post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for this post.', null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(255)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, help_text='Last editor of this post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, help_text='If this is a featured article.', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(help_text='Headline for this post.', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(120)], verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.BooleanField(default=False, help_text='If this is a site page article. Ex: privacy policy or terms & conditions.', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(editable=False, help_text='Cleaned up version of the title to be used in the URL.', max_length=120, verbose_name='Slug'),
        ),
    ]
