# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0019_auto_20160419_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
    ]
