# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleware', '0020_auto_20160419_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('author', 'headline', 'flavor')]),
        ),
    ]
