#!/bin/bash

# Ignoring autogenerated files
#  -- Migration directories
# Ignoring error codes
#  -- E124 closing bracket does not match visual indentation
#  -- E125 continuation line under-indented for visual indent for params
#  -- E128 continuation line under-indented for visual indent
#  -- E225 missing whitespace around operator
#  -- E501 line too long
#  -- E731 avoid lambda and use def

pep8 --exclude=migrations --ignore=E124,E125,E128,E225,E501,E731 .
