from django.conf import settings

PORTAL_TEMPLATE_BASE_DIR = getattr(settings, 'PORTAL_TEMPLATE_BASE_DIR', 'portal')
PORTAL_PAGINATION_NUMBER_PER_PAGE = 10
PORTAL_ARTICLE_SEARCH_CACHE_TIMEOUT_MINUTES = 10 * 60
PORTAL_ARTICLE_SUMMARY_CACHE_TIMEOUT_MINUTES = 15 * 60
