# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileware', '0002_auto_20160201_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_public',
        ),
    ]
