# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileware', '0003_remove_userprofile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, help_text='Your public email address. Everyone can see this. (Optional)', max_length=254, verbose_name='public email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, help_text='Your website address. (Optional)', max_length=120, verbose_name='website'),
        ),
    ]
