# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileware', '0004_auto_20160202_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.PositiveIntegerField(default=0, editable=False)),
                ('start', models.PositiveIntegerField(default=0, editable=False)),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='track', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
