# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileware', '0005_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='start',
            new_name='star',
        ),
    ]
