# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True, help_text='Third-party "Comment" Code. (e.g. Facebook, Disqus etc)', null=True, verbose_name='Comment Code')),
                ('active', models.BooleanField(default=True, help_text='If Active comments are enabled.', verbose_name='Active')),
            ],
        ),
    ]
