# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcode',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 4, 5, 16, 2, 15, 488208, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentcode',
            name='active',
            field=models.BooleanField(default=False, help_text='If Active comments are enabled.', verbose_name='Active'),
        ),
    ]
