# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteware', '0003_auto_20160414_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcode',
            options={'verbose_name': 'Comment'},
        ),
    ]
